language: R
sudo: required
cache: packages

r_github_packages:
  - hadley/r4ds
  - cienciadedatos/datos

before_script:
  - chmod +x ./scripts/cibuild

#before_install:                           # Install Ruby and html-proofer
#  - rvm get stable --auto-dotfiles
#  - rvm install 2.3.3
#  - gem install html-proofer

script:
  - ./scripts/cibuild

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: traduccion

#env:
#  global:
#    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speed up the html-proofer
