project:
  type: book
  output-dir: _book

book:
  title: "R for Data Science (2e)"
  reader-mode: true

  page-footer:
    left: |
      R for Data Science (2e) was written by Hadley Wickham, Mine
      Çetinkaya-Rundel, and Garrett Grolemund.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/hadley/r4ds/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - preface-2e.qmd
    - intro.qmd

    - part: whole-game.qmd
      chapters:
        - data-visualize.qmd
        - workflow-basics.qmd
        - data-transform.qmd
        - workflow-pipes.qmd
        - data-tidy.qmd
        - workflow-style.qmd
        - data-import.qmd
        - workflow-scripts.qmd
        - workflow-help.qmd

    - part: visualize.qmd
      chapters:
        - geoms-stats.qmd
        - positioning.qmd
        - scales.qmd
        - annotations-layout.qmd
        - EDA.qmd

    - part: transform.qmd
      chapters:
        - logicals.qmd
        - numbers.qmd
        - strings.qmd
        - regexps.qmd
        - factors.qmd
        - datetimes.qmd
        - missing-values.qmd
        - joins.qmd

    - part: wrangle.qmd
      chapters:
        - spreadsheets.qmd
        - databases.qmd
        - rectangling.qmd
        - webscraping.qmd

    - part: program.qmd
      chapters:
        - functions.qmd
        - iteration.qmd
        - base-R.qmd

    - part: communicate.qmd
      chapters:
        - quarto.qmd
        - quarto-formats.qmd
        - quarto-workflow.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

