project:
  type: book
  output-dir: _book

lang: tr

book:
  title: "Veri Bilimi için R (2e)"
  reader-mode: true

  page-footer:
    left: |
      R for Data Science (2e); Hadley Wickham, Mine Çetinkaya-Rundel ve Garrett Grolemund tarafından yazılmıştır.
    right: |
      Bu kitap <a href="https://quarto.org/">Quarto</a> ile oluşturulmuştur.

  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://tahaberk.com/r4ds-2e-tr/
  repo-url: https://github.com/TerekliTahaBerk/r4ds-2e-tr/
  repo-branch: translate-tr
  repo-actions: [edit, issue]

  other-links:
    - text: "Orijinal (English)"
      href: https://r4ds.hadley.nz/
      icon: mortarboard
    - text: "Çeviri (Türkçe)"
      href: https://tahaberk.com/r4ds-2e-tr/
      icon: translate

  chapters:
    - index.qmd
    - text: "Önsöz"
      file: preface-2e.qmd
    - text: "Giriş"
      file: intro.qmd

    - part: "Bütünsel Bakış"
      chapters:
        - text: "Veri Görselleştirme"
          file: data-visualize.qmd
        - text: "İş Akışı: Temeller"
          file: workflow-basics.qmd
        - text: "Veri Dönüştürme"
          file: data-transform.qmd
        - text: "İş Akışı: Stil"
          file: workflow-style.qmd
        - text: "Veri Düzenleme"
          file: data-tidy.qmd
        - text: "İş Akışı: Scriptler"
          file: workflow-scripts.qmd
        - text: "Veri Aktarımı"
          file: data-import.qmd
        - text: "İş Akışı: Yardım Almak"
          file: workflow-help.qmd

    - part: "Görselleştirme"
      chapters:
        - text: "Katmanlar"
          file: layers.qmd
        - text: "Keşifçi Veri Analizi"
          file: EDA.qmd
        - text: "İletişim"
          file: communication.qmd

    - part: "Dönüştürme"
      chapters:
        - text: "Mantıksal Vektörler"
          file: logicals.qmd
        - text: "Sayılar"
          file: numbers.qmd
        - text: "Karakter Dizileri"
          file: strings.qmd
        - text: "Düzenli İfadeler (Regex)"
          file: regexps.qmd
        - text: "Faktörler"
          file: factors.qmd
        - text: "Tarih ve Saatler"
          file: datetimes.qmd
        - text: "Eksik Değerler"
          file: missing-values.qmd
        - text: "Birleştirmeler (Joins)"
          file: joins.qmd

    - part: "Aktarma"
      chapters:
        - text: "Hesap Çizelgeleri"
          file: spreadsheets.qmd
        - text: "Veritabanları"
          file: databases.qmd
        - text: "Arrow"
          file: arrow.qmd
        - text: "Hiyerarşik Veriler"
          file: rectangling.qmd
        - text: "Web Kazıma"
          file: webscraping.qmd

    - part: "Programlama"
      chapters:
        - text: "Fonksiyonlar"
          file: functions.qmd
        - text: "İterasyon"
          file: iteration.qmd
        - text: "Temel R"
          file: base-R.qmd

    - part: "İletişim"
      chapters:
        - text: "Quarto"
          file: quarto.qmd
        - text: "Quarto Formatları"
          file: quarto-formats.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund"
    include-in-header: "plausible.html"
    callout-appearance: simple

language:
  tr:
    sidebar-title-other: "Bağlantılar"

editor: source
