on:
  push:
    branches: 
      - main
      - translate-tr  # Senin branch'ini ekledik
  pull_request:
    branches: 
      - main
      - translate-tr
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

name: build_book.yaml

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4 # Versiyonu güncelledik

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book to all format
        run: |
          quarto render

      - name: Upload website artifact
        # Sadece bu branchlerden biriyle tetiklenirse yükle
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/translate-tr' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_book"

  deploy:
    needs: build
    # Sadece translate-tr veya main ise deploy yap
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/translate-tr' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
